# Generated by Django 4.2.4 on 2023-11-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentmarket',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='currentmarket',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='currentmarket',
            name='percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='currentmarket',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='currentmarket',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='company_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='percentage_change',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='symbol',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='volume',
            field=models.BigIntegerField(null=True),
        ),
    ]
