# Generated by Django 4.2.4 on 2023-11-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmover', '0002_currentmarket_change_currentmarket_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmarket',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='currentmarket',
            name='volume',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='premarket',
            name='change',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='premarket',
            name='volume',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
