# Generated by Django 4.2.4 on 2023-11-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmover', '0003_alter_currentmarket_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentmarket',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='premarket',
            name='change',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
