# Generated by Django 4.2.4 on 2023-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketmover', '0004_alter_currentmarket_change_alter_premarket_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentmarket',
            name='table_reference',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='premarket',
            name='table_reference',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
