# Generated by Django 4.2.4 on 2023-10-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=50)),
                ('exchange_short_name', models.CharField(max_length=20)),
                ('stock_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StockProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('beta', models.FloatField()),
                ('last_div', models.FloatField()),
                ('stock_range', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('cik', models.CharField(max_length=20)),
                ('isin', models.CharField(max_length=20)),
                ('cusip', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=50)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('ceo', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('full_time_employees', models.PositiveIntegerField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=10)),
                ('dcf_diff', models.FloatField()),
                ('dcf', models.FloatField()),
                ('image', models.URLField()),
                ('ipo_date', models.DateField()),
                ('default_image', models.BooleanField(default=False)),
                ('is_etf', models.BooleanField(default=False)),
                ('is_actively_trading', models.BooleanField(default=True)),
                ('is_adr', models.BooleanField(default=False)),
                ('Is_fund', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percentage', models.FloatField()),
                ('change', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('day_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_high', models.DecimalField(decimal_places=2, max_digits=10)),
                ('year_low', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_cap', models.BigIntegerField()),
                ('price_avg_50', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_avg_200', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
                ('avg_volume', models.BigIntegerField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_close', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earning_per_share', models.FloatField()),
                ('price_to_earnings', models.FloatField()),
                ('earnings_announcement', models.DateTimeField()),
                ('shares_outstanding', models.BigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
