# Generated by Django 4.2.4 on 2023-10-31 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockList',
        ),
    ]
