# Generated by Django 4.2.4 on 2023-11-01 07:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_alter_stocklist_exchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
