# Generated by Django 4.2.4 on 2023-11-01 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_stocklist_created_at_stocklist_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockList',
        ),
    ]
