# Generated by Django 4.2.4 on 2023-11-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_stocklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklist',
            name='id',
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
