# Generated by Django 4.2.4 on 2023-11-02 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_remove_stocklist_id_alter_stocklist_symbol'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockprofile',
            old_name='Is_fund',
            new_name='is_fund',
        ),
    ]
