# Generated by Django 4.2.6 on 2023-11-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_rename_is_fund_stockprofile_is_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockprofile',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockprofile',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
