# Generated by Django 4.2.6 on 2023-11-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_remove_stockprofile_id_alter_stockprofile_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockquote',
            name='id',
        ),
        migrations.AlterField(
            model_name='stockquote',
            name='symbol',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
